name: Deploy Airflow repository

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GOOGLE_CLOUD_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  GCE_INSTANCE: airflow-xpln  # TODO: update to instance name
  GCE_INSTANCE_ZONE: europe-west-3   # TODO: update to instance zone
  SSH_KEY_FILE: ${{ secrets.SSH_KEY_FILE }}


on:
  push:
    branches: [ main ]
jobs:
  deploy-to-vm:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        
      - name: 'upload code'
        run: |
          gcloud compute scp dags/ alexissair@airflow-xpln:/home/alexissair/airflow-xpln/ --project=senselab-dev --zone=europe-west3-c --recurse
    



