name: Deploy Airflow repository

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GCE_INSTANCE: airflow-xpln  # TODO: update to instance name
  GCE_INSTANCE_ZONE: europe-west-3   # TODO: update to instance zone


on:
  push:
    branches: [ main ]
jobs:
  job_id:
    steps:
    - id: 'auth'
       name: 'Authenticate to Google Cloud'
       uses: 'google-github-actions/auth@v1'
       with:
         credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'ssh into the vm'
      run: 'gcloud compute ssh --zone "europe-west3-c" "airflow-xpln"  --project "senselab-dev"'
    
    - name: 'get code'
      run: 'git pull origin master'
    



