name: Deploy Airflow repository

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GCE_INSTANCE: airflow-xpln  # TODO: update to instance name
  GCE_INSTANCE_ZONE: europe-west-3   # TODO: update to instance zone


on:
  push:
    branches: [ main ]
jobs:
  deploy-to-vm:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'ssh into the vm'
        run: 'gcloud compute ssh --zone "europe-west3-c" "airflow-xpln"  --project "senselab-dev"'
      
      - name: 'upload code'
        run: ' gcloud compute scp ./airflow-xpln airflow-xpln:airflow-xpln --project=senselab-dev --zone=europe-west3-c'
    



